"""Bigframe"""
TEXT1_ = str(input()).strip(" ")
TEXT2_ = str(input()).strip(" ")
TEXT3_ = str(input()).strip(" ")
TEXT4_ = str(input()).strip(" ")
TEXT5_ = str(input()).strip(" ")
NUM_ = max(len(TEXT1_), len(TEXT2_), len(TEXT3_), len(TEXT4_), len(TEXT5_))
print("*"*(NUM_+4))
print("* "+TEXT1_+" "*(NUM_-len(TEXT1_))+" *")
print("* "+TEXT2_+" "*(NUM_-len(TEXT2_))+" *")
print("* "+TEXT3_+" "*(NUM_-len(TEXT3_))+" *")
print("* "+TEXT4_+" "*(NUM_-len(TEXT4_))+" *")
print("* "+TEXT5_+" "*(NUM_-len(TEXT5_))+" *")
print("*"*(NUM_+4))
